[tool.poetry]
name = "poof"
version = "1.0.0"
description = ""
authors = ["pr3d4t0r <poof.project@cime.net>"]

[tool.poetry.dependencies]
python = "3.8.5"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
