#!/bin/bash
# See: https://github.com/poof-backup/poof/blob/master/LICENSE.txt


# +++ main +++

mkdir -p "$HOME/Library/Application Support/poof"
cp poof_conf.bak poof.conf
cp rclone_conf.bak rclone.conf

