#!/bin/zsh

# +++ constants +++

PACKAGE_NAME="poof"


function die {
    echo "$1"
    exit "$2"
} # die


function assertNoVirtualenv {
    [[ -n "$VIRTUAL_ENV" ]] && die "exit VIRTUAL_ENV = $VIRTUAL_ENV to continue" 1
} # assertNoVirtualenv


function prepareResourceStanzas {
    # Ref: https://docs.brew.sh/Python-for-Formula-Authors
    # section Installing.

    # cd "$(mktemp -d)"
    python3 -m venv venv
    source venv/bin/activate

    pip install -U pip

    pip install "$PACKAGE_NAME" homebrew-pypi-poet

    poet "$PACKAGE_NAME"

    deactivate

    rm -Rf venv
} # prepareResourceStanzas


# +++ main +++

assertNoVirtualenv
prepareResourceStanzas

exit 0

